### ISSUE TITLE
[Bug]: bi command doesn't work

### ISSUE THREAD

**Issue by fengqiangzhao** [chrisgrieser/alfred-homebrew#5]
### Bug Description

When I first run this command, it doesn't work, and show this error message on screenshot

### Relevant Screenshot

<img width="1722" alt="image" src="https://github.com/chrisgrieser/alfred-homebrew/assets/31373172/8936e6a7-fcea-4dde-aa25-97ee87f43455">

### Debugging Log

```Text
[17:39:05.120] Homebrew[Script Filter] Queuing argument '(null)'
[17:39:06.483] Homebrew[Script Filter] Script with argv '(null)' finished
[17:39:06.488] ERROR: Homebrew[Script Filter] Code 1: Cache Dir does not exist and is created.
/Users/fengqiangzhao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EAB9188E-8FFE-4DA9-8842-76F77139A219/scripts/brew-install.js: execution error: Error: Error: 发生错误。 (-1743)
```

### Workflow Configuration

<img width="1200" alt="image" src="https://github.com/chrisgrieser/alfred-homebrew/assets/31373172/e8c6c1a6-d4e9-4fff-af25-f83f2db214c0">

### Checklist

- [X] I have [updated to the latest version](./releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Could you run the following in your terminal and share the output?:

```bash
brew update
brew --prefix
brew --version
```

Also, I made a new release which includes some more logging. Could you install this version and see what is reported in the debugging log now?

**Comment by chrisgrieser** [comment]
Closing since inactionable without further input.

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “[Bug]: bi command doesn't work”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
